#include<iostream>
using namespace::std;
//Calculate the largest palindrome generated by multiplication of 2 numbers 
int palindrome(long int a) //Palindrome checker
{
    int b=a;
    int rev=0;
    while(a)
    {
        rev=rev*10+a%10;
        a=a/10;
    }
    if(rev==b)
    {
        return 1;
    }
    else
    {
        return 0;
    }
    
}
int main()
{
    long int n;
    long int max=0;
    for(long int i=999;i>=100;i--)//Iterating through every combinations 
    {
        for(long int j=999;j>=101;j--)
        {
            n=i*j;
            if(palindrome(n)==1)
            {
               if(n>=max)
               {
                   max=n;
               }
            }
        }
       
    }
    cout<<"Largest Palindrome "<<max;
    return 0;

}